name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@main
        with:
          github_user_name: andref218
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: ./assets/github-snake.svg

      - name: Commit SVG if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./assets/github-snake.svg
          git diff --cached --quiet || git commit -m "Update GitHub Snake" || echo "Nothing to commit"
          git push || echo "Push failed (check branch protection)"
