name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure assets folder exists
        run: mkdir -p assets

      - name: Generate Snake
        uses: platane/snk@main
        with:
          github_user_name: andref218
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: ./assets/github-snake.svg

      - name: Commit and push SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub Snake"
          branch: main
          file_pattern: "assets/github-snake.svg"
